export { default as Logo } from './Logo/Logo'
export { default as Tabs } from './Tabs/Tabs'
export { default as TabList } from './Tabs/TabList'
export { default as Tab } from './Tabs/Tab'
export { default as TabPanels } from './Tabs/TabPanels'
export { default as TabPanel } from './Tabs/TabPanel'
export { default as Skill } from './Skill/Skill'
export { default as AsideMenu } from './AsideMenu/AsideMenu'